use crate::geometry::{RectF, SizeF};
use crate::platform::*;
use crate::security;
use crate::policy_values;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    CallbackFailed,
    CreateFailed,
    FocusFailed,
    CloseFailed,
}

pub struct MacPlatform {
    app_info: AppInfo,
    surface_value: Surface,
    web_engine: WebEngine,
}

impl MacPlatform {
    pub fn new(size: SizeF, web_engine: WebEngine, app_info: AppInfo) -> Self {
        Self {
            app_info,
            surface_value: Surface { id: 1, size, scale_factor: 1.0 },
            web_engine,
        }
    }

    pub fn surface(&self) -> &Surface { &self.surface_value }
    pub fn app_info(&self) -> &AppInfo { &self.app_info }
    pub fn web_engine(&self) -> WebEngine { self.web_engine }
}

/// Linux platform backend — uses GTK4 + WebKitGTK via FFI.
/// The native C code is compiled by build.rs from ../zero-native/src/platform/linux/gtk_host.c
/// and the header bindings are generated by bindgen.
pub struct LinuxPlatform {
    app_info: AppInfo,
    surface_value: Surface,
    web_engine: WebEngine,
}

impl LinuxPlatform {
    pub fn new(size: SizeF, web_engine: WebEngine, app_info: AppInfo) -> Self {
        Self {
            app_info,
            surface_value: Surface { id: 1, size, scale_factor: 1.0 },
            web_engine,
        }
    }

    pub fn surface(&self) -> &Surface { &self.surface_value }
    pub fn app_info(&self) -> &AppInfo { &self.app_info }
    pub fn web_engine(&self) -> WebEngine { self.web_engine }
}

/// Windows platform backend — uses WebView2 via FFI.
/// The native C++ code is compiled by build.rs from ../zero-native/src/platform/windows/webview2_host.cpp
pub struct WindowsPlatform {
    app_info: AppInfo,
    surface_value: Surface,
    web_engine: WebEngine,
}

impl WindowsPlatform {
    pub fn new(size: SizeF, web_engine: WebEngine, app_info: AppInfo) -> Self {
        Self {
            app_info,
            surface_value: Surface { id: 1, size, scale_factor: 1.0 },
            web_engine,
        }
    }

    pub fn surface(&self) -> &Surface { &self.surface_value }
    pub fn app_info(&self) -> &AppInfo { &self.app_info }
    pub fn web_engine(&self) -> WebEngine { self.web_engine }
}

/// Detect the current platform at compile time.
pub fn current_backend() -> &'static str {
    if cfg!(target_os = "macos") { "macos" }
    else if cfg!(target_os = "linux") { "linux" }
    else if cfg!(target_os = "windows") { "windows" }
    else { "unknown" }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mac_platform_creates_with_options() {
        let app_info = AppInfo { app_name: "Test".into(), ..Default::default() };
        let platform = MacPlatform::new(SizeF::new(800.0, 600.0), WebEngine::System, app_info);
        assert_eq!("Test", platform.app_info().app_name);
    }

    #[test]
    fn linux_platform_creates_with_options() {
        let app_info = AppInfo { app_name: "Test".into(), ..Default::default() };
        let platform = LinuxPlatform::new(SizeF::new(800.0, 600.0), WebEngine::System, app_info);
        assert_eq!("Test", platform.app_info().app_name);
    }

    #[test]
    fn windows_platform_creates_with_options() {
        let app_info = AppInfo { app_name: "Test".into(), ..Default::default() };
        let platform = WindowsPlatform::new(SizeF::new(800.0, 600.0), WebEngine::System, app_info);
        assert_eq!("Test", platform.app_info().app_name);
    }

    #[test]
    fn current_backend_matches_os() {
        let backend = current_backend();
        if cfg!(target_os = "macos") { assert_eq!("macos", backend); }
        if cfg!(target_os = "linux") { assert_eq!("linux", backend); }
    }
}
